### ISSUE TITLE
question mark / Help button

### ISSUE THREAD

**Issue by lucidqdreams** [duongngocmanh/Gunbot-CW-Controller#3]
![image](https://user-images.githubusercontent.com/6086602/60552539-1593e000-9ce4-11e9-86f4-654b3dafb3ff.png)
??

I would say this should just redirect to a wiki for updated help/ how to use

**Comment by duongngocmanh** [comment]
Ty for your report. This will be remade in the next update. The question mark will show up some basic guidelines.
